#!/bin/bash

if [[ -d /dx/apps/jd2 ]] ; then
	# Run JDownloader
	/bin/sh "/dx/apps/jd2/JDownloader2"
 else
	echo "Dungeon Closed. No JDownloader"
	notify-send "Dungeon Closed. No JDownloader"
	exit
fi
