#!/bin/bash

# Help
_help_show() {
	echo "Syntax: $(basename "$0") -i <input video> -f <fps> -n <times N>"
}

while getopts ":hi:f:n:" opt ; do
	#echo "Processing $opt : OPTIND is $OPTIND"
	case $opt in
		h) _help_show ;;
		i) in_file="$OPTARG" ;;
		f) in_fps="$OPTARG" ;;
		n) in_timesN="$OPTARG" ;;
		:) echo "Error: -$OPTARG requires an argument" ; exit 1 ;;
		?) echo "Error: unknown option -$OPTARG" ; exit 1 ;;
	esac
done
shift "$((OPTIND-1))"

extn="${in_file##*.}"
out_file="_M$(date +%H%M%S).${extn}" # Concatenated output filename.

python3 "/opt/Super-SloMo/video_to_slomo.py" \
	--video="${in_file}" \
	--sf="${in_timesN}" \
	--checkpoint="/opt/Super-SloMo/SuperSloMo.ckpt" \
	--fps="${in_fps}" \
	--output="${out_file}"
