#!/usr/bin/env bash
# Script Name : xvs
# Description : Provides various features to manipulate a video file.
# Args        : Refer HELP section for usage.
# Author      : Madhusudhan D Desai
# Email       : mddnix@gmail.com

source BashLib.sh

# Bash shell options
# ------------------
set -o nounset # Exit when script tries to use undeclared variables.
set -o errexit # Exit script when command fails. Add '|| true' to allow fail.

# Constant variables
# ------------------
readonly CURRENT_DIR="$PWD"
readonly SCRIPT_NAME=$(basename $0)
readonly XDIR="/xd"
readonly NDIR="/nd"
readonly XDEV="/dev/sda4"
readonly NDEV="/dev/sda8"
readonly XMAP="XDDM"
readonly NMAP="NDDM"
readonly XUSR="neon"
readonly NUSR="neon"

# Global variables
# ----------------
declare -a info_video=()
mount_dir=
umount_dir=
slow_video=
audio_file=
fade_audio=
volume=

# Check if necessary commands are installed
# -----------------------------------------
_is_cmd "cryptsetup"
_is_cmd "fuser"
_is_cmd "install"
_is_cmd "ffmpeg"
_is_cmd "ffprobe"

###################################################################################################
# Delete temp files from the directory where the script has been executed.
# Globals/Constants:
#   CURRENT_DIR
###################################################################################################
_trap_cleanup() {
	echo "Oops! $(basename $0) ($$) has terminated."
	echo "Cleaning temporary files (if any)..."
	find "${CURRENT_DIR}" -type f -name "tmp_xvs_*.mp4" -print -delete
	echo "Done"
	exit 2
}
trap '_trap_cleanup' SIGHUP SIGINT SIGQUIT SIGQUIT SIGTERM

###################################################################################################
# Show help.
###################################################################################################
_help_show() {
cat <<HELP
Usage: 
 ${SCRIPT_NAME} [OPTIONS]...

Options:
 -h            Help.   Show this help.
 -c [file]...  Concat. Concatenate several videos.
 -i [file]...  Info.   Show info of video(s).
 -m [xn]       Mount.  Mounts LUKS partition into directory.
 -s [file]     Slow.   Create slowmotion video.
 -t            Tags.   Display metadata tags.
 -u [xn]       Umount. Unmount LUKS partition from directory.
HELP
}

###################################################################################################
# Concatenate one or several videos.
# Arguments:
#   $1...: Array of input video file.
# Return:
#   Concatenated video file.
###################################################################################################
_cnct_video() {
	local files=
	local output=
	local ctr=1
	local sec=0
	local secs=0
	declare -a get_video_info=()
	declare -a get_audio_info=()

	# Club video filenames with '|' inbetween them.
	for i ; do
		get_video_info=($(mediainfo --fullscreen \
			--Inform="Video;%DisplayAspectRatio/String% %FrameRate% %Format% %Duration%" "$i"))
		
		get_audio_info=($(mediainfo --fullscreen \
			--Inform="Audio;%Format% %SamplingRate% %Channel(s)%" "$i"))

		# Print video information
		printf "%2d %8s %7s  %-7s %-7s %5s %3s %6.2f  %s\n" \
			$(( ctr++ )) \
			"${get_video_info[0]}" \
			"${get_video_info[1]}" \
			"${get_video_info[2]}" \
			"${get_audio_info[0]}" \
			"${get_audio_info[1]}" \
			"${get_audio_info[2]}" \
			"$(echo "${get_video_info[3]}"/1000|bc -l)" \
			"${i}" 
		sec=$(echo "scale=2;(${get_video_info[3]})/1000"|bc -l)
		secs=$(echo "scale=2;($secs+$sec)/1"|bc -l)
		files="$files|$i"
	done
	echo "TOTAL: ${secs}"
	files=${files#|*} # Remove '|' at beginning.
	output="_C$(date +%H%M%S).avi" # Concatenated avi output filename.

	# Print output command for reference
	echo
	echo "[#" ffmpeg -v error -hide_banner -stats \
		-i concat:"${files}" \
		-c copy "${output}" "#]"
	
	# Start concatenating.
	ffmpeg -v error -hide_banner -stats \
		-i concat:"${files}" \
		-c copy "${output}"
}

###################################################################################################
# Shows short info of video file(s).
# Arguments:
#   $1...: Array of video filenames
# Return:
#   Short info of video file(s).
###################################################################################################
_info_video() {
	for i ; do
		echo "${i}:" # Print video file name
		ffprobe "${i}" 2>&1 | egrep "Duration|Stream" # ffprobe short info
		echo
	done
}

###################################################################################################
# Join video(s) with audio.
# Arguments:
#   $1: Audio file.
#   $2: Volume level.
#   $3: Fadeout seconds.
#   $4...: Video file(s). 
# Return:
#   Joined video witj custom audio file.
###################################################################################################
_join_video() {
	local in_audio="$1"   # Audio filename.
	local in_volume="$2"  # Audio volume.
	local in_fade="$3"    # Audio fadeout.
	shift 3               # Move to next 3 argument.
	local in_video=("$@") # Array of video filenames.

	declare -a get_video_info=()
	local ctr=1
	local files=    # Holds concatenated file name(s).
	local sec=0     # Holds seconds of individual video file.
	local secs=0    # Holds Total duration in seconds of all files.
	local bg_audio= # Holds background audio file.
	local afilter=  # Holds audio filter.
	local end_dur=  # Holds total seconds - 1.
	local output=   # Joined avi output filename.
	output="_J$(date +%H%M%S).avi" # Output joined video filename.


	# Find duration of all videos + Join video filenames with '|' inbetween them.
	_draw_line "-"
	for i in "${in_video[@]}" ; do
		get_video_info=($(mediainfo --fullscreen \
			--Inform="Video;%DisplayAspectRatio/String% %FrameRate% %Duration%" "$i"))

		sec=$(echo "${get_video_info[2]}/1000"|bc -l) # Duration of each videos.
		
		secs=$(echo "scale=2;($secs+$sec)/1"|bc -l) # Total duration of all video files.
		files="$files|$i" # Join video filename with '|' inbetween.

		# Print video information
		printf "%2d %8s %7s %6.2f %s\n" \
			$(( ctr++ )) \
			"${get_video_info[0]}" \
			"${get_video_info[1]}" \
			"${sec}" \
			"${i}" 
	done
	echo "TOTAL: ${secs} seconds"
	files=${files#|*} # Trim beginning | character.

	# Set background audio.
	if [[ -n "${in_audio}" ]] ; then
		bg_audio="-i ${in_audio} -shortest" # Audio file selected.
	else
		bg_audio="-f lavfi -i anullsrc -shortest"
	fi

	# Set volume level
	if [[ -n "${in_volume}" && -z "${in_fade}" ]] ; then # If only volume is given
		afilter="-af volume=${in_volume}"

	elif [[ -n "${in_fade}" && -z "${in_volume}" ]] ; then # If only fadeout is given
		end_dur=$(echo "scale=2;($secs-$in_fade)/1"|bc -l)
		afilter="-af afade=in:st=0:d=1,afade=out:st=${end_dur}:d=${in_fade}"

	elif [[ -n "${in_volume}" && -n "${in_fade}" ]] ; then # If both volume and fadeout is given
		end_dur=$(echo "scale=2;($secs-$in_fade)/1"|bc -l)
		afilter="-af volume=${in_volume},afade=out:st=${end_dur}:d=${in_fade}"
	else
		afilter="" # No setting
	fi

	_draw_line "-"
	echo ffmpeg -v error -hide_banner -stats \
		-i concat:"${files}" \
		${bg_audio} \
		-c:v rawvideo -vtag YV12 -pix_fmt yuv420p -vf shuffleplanes=0:2:1 \
		-c:a pcm_s16le -ar 48000 -ac 2 \
		${afilter} \
		-map 0:v -map 1:a \
		${output}
	_draw_line "-"

	# Start concatenating.
	ffmpeg -v error -hide_banner -stats \
		-i concat:"${files}" \
		${bg_audio} \
		-c:v rawvideo -vtag YV12 -pix_fmt yuv420p -vf shuffleplanes=0:2:1 \
		-c:a pcm_s16le -ar 48000 -ac 2 \
		${afilter} \
		-map 0:v -map 1:a \
		${output}
}

###################################################################################################
# Mounts the LUKS partition into a directory. Creates directory if necessary.
# Globals/Constants:
#   XDEV, XDIR, XMAP, XUSR, NDEV, NDIR, NMAP, NUSR
###################################################################################################
_mount_dir() {

	# Check if $1 has correct values - x or n.
	if [[ "$1" = "x" ]] ; then
		local dev_name="${XDEV}"
		local dir_name="${XDIR}"
		local map_name="${XMAP}"
		local usr_name="${XUSR}"
	elif [[ "$1" = "n" ]] ; then
		local dev_name="${NDEV}"
		local dir_name="${NDIR}"
		local map_name="${NMAP}"
		local usr_name="${NUSR}"
	else
		echo "Couldn't find mount code... exiting."
		exit 1
	fi

	# Check if mount directory already (not) exist.
	if [[ ! -d "${dir_name}" ]] ; then
		echo "Directory '${dir_name}' does not exist. Creating it..."
		sudo install -o "${usr_name}" -g "${usr_name}" -m 0770 -d "${dir_name}" # Create dirctory.
		if [[ $? -eq 0 ]] ; then
			echo "...Done." 
		else 
			echo "Error: Couldn't create directory ${dir_name}."
			exit 1
		fi
	fi

	# Check if LUKS device already mounted into a directory.
	if [[ $(findmnt -M "${dir_name}") ]] ; then
		echo "${dir_name} already mounted with ${dev_name}. Doing nothing."
		exit 1
	else
		# Check if are in mount directory.
		if [[ "$(echo $PWD)" = "${dir_name}" ]] ; then # You are inside mount point is TRUE. 
			echo "You are inside the mount directory ${dir_name}. Change directory and try again."
			exit 1
		fi
		echo "Mounting ${dev_name} into ${dir_name} ..."
		sudo cryptsetup open --type luks2 "${dev_name}" "${map_name}" # Open LUKS device.
		sudo mount "/dev/mapper/${map_name}" "${dir_name}" # Mount LUKS device in a directory.
		if [[ $? -eq 0 ]] ; then
			echo "${dir_name} mounted. Ready to use."
		else
			echo "Error: Couldn't mount ${dir_name}... Exiting."
			exit 1
		fi
	fi
}

###################################################################################################
# Slows down video file.
# Arguments:
#   $1: Input video file.
# Return:
#   Slowmotion video file
###################################################################################################
_slow_video() {
	local input="$1" # vid.mkv
	local get_info=$(mediainfo --fullscan \
		--Inform="Video;%Duration% %FrameRate%" "$input") # 3504.000000 23.976
	local sec=$(echo "scale=3;${get_info% *}/1000"|bc -l) # 3.504
	local fps=${get_info#* }                              # 23.976
	local calc_total_frames=$(echo "$sec*$fps"|bc -l)     # 84.011904 
	local orig_frame=${calc_total_frames%.*}              # 84
	local frm=$(( orig_frame - 2 ))                       # 82
	#echo "$input | $get_info | $sec | $fps | $calc_total_frames | $orig_frame | $frm"

	# Print header
	echo "%%% SOURCE: ${input}, ${sec} secs, ${fps} fps, ${orig_frame} frames."
	_draw_line '=' 32
	printf "%4s%8s%7s%9s\n" "#" "FRAME" "SECS" "TIME"
	_draw_line '=' 32

	# Give prediction for 20 seconds
	for i in {1..20} ; do
		local tot_frm=$(( i*frm )) # First iteration: (1x82)=82
		local tot_sec=$(echo "scale=2;$tot_frm/$fps"|bc -l) # First iteration: (82/23.976)=3.42
		local tot_clk=$(date -d@$tot_sec -u +%M:%S.%2N)
		printf "%4d%7d%8.2f%11s\n" "$i" "$tot_frm" "$tot_sec" "$tot_clk"
	done

	# Print tail and ask for slowmotion times.
	_draw_line '-' 32
	read -p "  n? " timesN
	if [[ "${timesN}" = "q" ]] ; then
		exit 0
	fi

	# Final variable calulation for output.
	local op_total_frames=$(echo "scale=0;($timesN*$frm)/1"|bc -l) # Output video total frames.
	local op_mid_mfps=$(echo "$timesN*$fps"|bc -l) # Required minterpolate fps (float).
	local op_total_mfps=$(printf "%.f" $op_mid_mfps) # Output minterpolate fps (round).
	local op_total_sec=$(echo "scale=2;$op_total_frames/$fps"|bc -l) # Output total seconds.
	local op_total_clk=$(date -d@$op_total_sec -u +%M:%S.%2N) # output total time in clock.
	local output="_S${input}_$(date +%H%M%S)_${timesN}_${op_total_sec}.avi" # Output raw avi filename.

	# Print output file details.
	echo
	echo ffmpeg -v error -hide_banner -stats \
		-i "${input}" \
		-f lavfi -i anullsrc -shortest \
		-c:v rawvideo -vtag YV12 -pix_fmt yuv420p \
		-vf "shuffleplanes=0:2:1,minterpolate='fps=${op_total_mfps}',setpts='${timesN}*PTS',fps='fps=${fps}'" \
		-c:a pcm_s16le -ar 48000 -ac 2 \
		-map 0:v -map 1:a \
		-sn -map_chapters -1 \
		-f avi "${output}"
	echo "%%% TARGET: ${output}, ${op_total_mfps} mfps, ${op_total_frames} frames, ${op_total_clk} duration. "
	echo

	# Start encoding slowmotion video
	ffmpeg -v error -hide_banner -stats \
		-i "${input}" \
		-f lavfi -i anullsrc -shortest \
		-c:v rawvideo -vtag YV12 -pix_fmt yuv420p \
		-vf "shuffleplanes=0:2:1,minterpolate='fps=${op_total_mfps}',setpts='${timesN}*PTS',fps='fps=${fps}'" \
		-c:a pcm_s16le -ar 48000 -ac 2 \
		-map 0:v -map 1:a \
		-sn -map_chapters -1 \
		-f avi "${output}"
	sync
}

###################################################################################################
# Lists tags for metadata.
# E: openssl aes-256-cbc -md sha256 -salt -pbkdf2 -iter 1024 -a -in clear1.txt -out encrypt.enc
# D: openssl aes-256-cbc -md sha256 -salt -pbkdf2 -iter 1024 -a -d -in encrypt.enc -out clear2.txt
###################################################################################################
_tags_list() {
Tags() {
cat <<EOF
U2FsdGVkX18oEeaG3t2foUbNkGI4SmiE1mpA79WnUvBp2ayWTkM8xX0EK8kSm0sn
DDEYaZmOBV5crSMnEq6ckOB3hNKtFlOFl3C+D0VeSQ7E5evywvRSzQhVXSd5BtSo
o5LtKLaah/TtrY/2kBiZpe9W0dFsRJ+wI70x4xR9cAfdBBI6rWpPraaqmPQWIYlv
BVBuWbxCwHgivIpUii+p9Xw3kZNHcKOpFMe9c6ldGTVuAegDAAJoPdh4lRawKZjp
wyQQOiyhdlVhf+EFUNDXTAPYkl4c5VApgP1PumksH5VZ8XO0qyMnub3kWceprs5L
mz+nwZxpemURUbJeCWPl9H4XRpn3TFKOwhv2xFDjGQprYgEphjGtO90TWzoDGcgF
i4uV7PJjHRQLO7waa0vIpAOxTSx16MiBqgtxIGbUjZjRT4M63SQ0nIDAIvMn6eLO
mR4JPHwX6ImbSvVNstSS80vxWZ5/paXjHGkQKvuo8rQjTyukHDRSUDYdGXBJQO6Y
6QYJsv4Itu1roEEhr1N17tS5i919ZJAxfFVtac3eOKnmDCvlpwc1EySmT7cqwKKX
HIeyjZTvgkxOlMAMabyCLEJWTGORudbmZV3Bkdh6Slg/NYBnI5wBU8EBsZwh1i3J
nrXtCLZmqvSa5TDw+4zQK9mJIeNZ2fbrome5tL17Fi1a4RU0iE8zv74/Ir7ihpg3
s1GtxduQCGG7hdSS9gEXOqb2+G2v+zKyFWN5QGhjkNHepx7woFZmbwkUmRegKTM6
YstwW9Yk2OTNcj5VY9nAqTpqXAwGrKdY/vgwWoNygVpX51C/00Xngbwx8YDelxgR
xhNKhyo+bfp4TUG7f16ErBOngDCXlFP3XyafHg8w3Z4=
EOF
}

	# Store decrypted tags in valriable. Needs password.
	local var_tags=$(Tags | openssl aes-256-cbc -md sha256 -salt -pbkdf2 -iter 1024 -a -d 2>/dev/null)
	if [[ "${var_tags}" =~ Birthday ]] ; then
		echo
		_title_header "$(_to_upper 'Available Tags')" '>' '<'
		echo "${var_tags}" | column
		echo
	else
	    echo "Sorry! Wrong password. Exiting..."
		exit 1
	fi
}


###################################################################################################
# Unmounts the LUKS partition from a directory.
# Globals/Constants:
#   XDEV, XDIR, XMAP, XUSR, NDEV, NDIR, NMAP, NUSR
###################################################################################################
_umount_dir() {

	# Check if $1 has correct values - x or n.
	if [[ "$1" = "x" ]] ; then
		local dev_name="${XDEV}"
		local dir_name="${XDIR}"
		local map_name="${XMAP}"
		local usr_name="${XUSR}"
	elif [[ "$1" = "n" ]] ; then
		local dev_name="${NDEV}"
		local dir_name="${NDIR}"
		local map_name="${NMAP}"
		local usr_name="${NUSR}"
	else
		echo "Couldn't find mount code... exiting."
		exit 1
	fi

	# Check if are unmounting from source directory.
	if [[ "$(echo $PWD)" = "${dir_name}" ]] ; then
		echo "You are inside to-be un-mount directory ${dir_name}. Change directory and try again."
		exit 1
	fi

	# Check if directory is already mounted.
	if [[ $(findmnt -M "${dir_name}") ]] ; then
		echo "Unmounting ${dir_name}..."

		# Check if the mount directory is busy
		if [[ $(sudo fuser --mount "${dir_name}") ]] ; then
			sudo fuser -kvi "${dir_name}" # Kill all busy processes interactively.
		fi
		
		# Lazy umount the directory, then, if successful, close LUKS
		sudo umount -l "${dir_name}"
		if [[ $? -eq 0 ]] ; then
			sudo cryptsetup close "${map_name}" # Close LUKS
			if [[ $? -eq 0 ]] ; then
				echo ""${dir_name}" unmounted.. Done."
			fi
		fi
	else
		echo "${dir_name} not mounted. Doing nothing."
	fi
}


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%% Main Function
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
while getopts ":ha:c:f:i:j:m:s:tu:v:" opt ; do
	#echo "Processing $opt : OPTIND is $OPTIND"
	case $opt in
		h) _help_show ;;
		a) audio_file="$OPTARG" ;;
		c) cnct_video+=("$OPTARG") ;;
		f) fade_audio="$OPTARG" ;;
		i) info_video+=("$OPTARG") ;;
		j) join_video+=("$OPTARG") ;;
		m) mount_dir="$OPTARG" ;;
		s) slow_video="$OPTARG" ;;
		t) _tags_list ;;
		u) umount_dir="$OPTARG" ;;
		v) volume="$OPTARG" ;;
		:) echo "Error: -$OPTARG requires an argument" ; exit 1 ;;
		?) echo "Error: unknown option -$OPTARG" ; exit 1 ;;
	esac
done
shift "$((OPTIND-1))"


# Concatenate Videos function.
if [[ -n "${cnct_video[@]}" && "${#cnct_video[@]}" -gt 1 ]] ; then
	_cnct_video "${cnct_video[@]}"
fi

# Info Videos function.
if [[ -n "${info_video[@]}" ]] ; then
	_info_video "${info_video[@]}" 
fi

# Join Videos function with only videos.
if [[ -n "${join_video[@]}" && -z "${audio_file}" && -z "${volume}" && -z "${fade_audio}" ]] ; then
	_join_video "" "" "" "${join_video[@]}"

# Join Videos function with videos and audio.
elif [[ -n "${join_video[@]}" && -n "${audio_file}" && -z "${volume}" && -z "${fade_audio}" ]] ; then
	_join_video "${audio_file}" "" "" "${join_video[@]}" 

# Join Videos function with videos, audio and volume.
elif [[ -n "${join_video[@]}" && -n "${audio_file}" && -n "${volume}" && -z "${fade_audio}" ]] ; then
	_join_video "${audio_file}" "${volume}" "" "${join_video[@]}" 

# Join Videos function with videos, audio and fade-out.
elif [[ -n "${join_video[@]}" && -n "${audio_file}" && -z "${volume}" && -n "${fade_audio}" ]] ; then
	_join_video "${audio_file}" "" "${fade_audio}" "${join_video[@]}" 

# Join Videos function with videos, audio, volume and fade-out.
elif [[ -n "${join_video[@]}" && -n "${audio_file}" && -n "${volume}" && -n "${fade_audio}" ]] ; then
	_join_video "${audio_file}" "${volume}" "${fade_audio}" "${join_video[@]}" 
fi

# Mount device into a folder.
if [[ ! -z "$mount_dir" ]] ; then
	_mount_dir "${mount_dir}"
fi

# Slowmotion videos.
if [[ ! -z "$slow_video" ]] ; then
	_slow_video "${slow_video}"
fi

# Unmount device from folder.
if [[ ! -z "$umount_dir" ]] ; then
	_umount_dir "${umount_dir}"
fi
